title: Hello, world! I'm LUOXC
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://luoxc.xyz" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 饭团 # add your name
author-img: https://avatars3.githubusercontent.com/u/4321114?s=400&v=4 # add your photo
about-author: 我是一个java程序员，喝了大量咖啡无数心血致力于数据分析。 # add description
# twitter: # add your Twitter handle
# facebook: # add your Facebook handle
github: luoxc # add your Github handle
# linkedin: # add your Linkedin handle
email: lxc1317@hotmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
